[package]
name = "m_client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "m_client"
path = "src/main.rs"

[dependencies]
m_core = { path = "../m_core" }

serde = { version = "1.0", features = ["derive"] }
toml = "0.9.8"
hex = "0.4"
clap = { version = "4", features = ["derive"] }

tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tokio-util = "0.7"
ratatui = "0.29"
crossterm = "0.28"
tonic = "0.11"
prost = "0.12"
chrono = "0.4"
anyhow = "1"
uuid = { version = "1.22", features = ["v4"] }
shellexpand = "3"
torut = "0.2"
tokio-socks = "0.5"
bincode = "1.3"
